export const FETCH_POST_LIST_REQUEST = 'FETCH_POST_LIST_REQUEST';  //요청보내는 시점
export const FETCH_POST_LIST_SUCCESS = 'FETCH_POST_LIST_SUCCESS';  //응답이 성공
export const FETCH_POST_LIST_FAILURE = 'FETCH_POST_LIST_FAILURE';  //응답이 실패


