export const FETCH_POST_DETAIL_REQUEST = 'FETCH_POST_DETAIL_REQUEST';  //요청보내는 시점
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';  //응답이 성공
export const FETCH_POST_DETAIL_FAILURE = 'FETCH_POST_DETAIL_FAILURE';  //응답이 실패


